name: Push VL.Xlsx Nuget

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Patch Version from tag
        run: |
          cd .nuget
          .\patch-version.cmd "VL.Xlsx.nuspec" "${{ github.ref_name }}"
          cd ..

      - name: Build VL.Xlsx
        run: |
          msbuild .\src\Xlsx.csproj -t:build -restore /property:Configuration=Release /property:Platform=x64

      - name: Publish VL Nuget
        uses: vvvv/PublishVLNuget@1.0.43
        with:
          nuspec: .nuget\VL.Xlsx.nuspec
          nuget-key: ${{ secrets.NUGET_KEY }}
